# Generated by Django 6.0.2 on 2026-03-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=120)),
                ('invested_equity', models.DecimalField(decimal_places=2, max_digits=14)),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('mortgage_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('annual_rent_income', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('annual_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['property_name'],
            },
        ),
    ]
