# Generated by Django 5.2.12 on 2026-04-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyinvestment',
            options={'ordering': ['ownership_category', 'property_name']},
        ),
        migrations.AddField(
            model_name='propertyinvestment',
            name='ownership_category',
            field=models.CharField(choices=[('joint', 'Conjunta'), ('ximo', 'Ximo'), ('monica', 'Monica')], default='joint', max_length=12),
        ),
    ]
