# Generated by Django 6.0.2 on 2026-03-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neos_ceramica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeramicaAnnualValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('ownership_pct', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('balance_approved', models.BooleanField(default=False)),
                ('audited_favorable', models.BooleanField(default=False)),
                ('balance_pdf', models.FileField(blank=True, upload_to='neos_ceramica/annual/%Y')),
                ('profit_loss_pdf', models.FileField(blank=True, upload_to='neos_ceramica/annual/%Y')),
                ('corporate_tax_pdf', models.FileField(blank=True, upload_to='neos_ceramica/annual/%Y')),
                ('net_equity', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('share_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('profit_after_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('three_year_average_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('capitalised_earnings_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('tax_company_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('owner_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('valuation_method', models.CharField(blank=True, choices=[('audited_balance', 'Audited approved balance'), ('theoretical_value', 'Theoretical book value'), ('earnings_capitalisation', 'Capitalised 3-year earnings'), ('nominal_value', 'Nominal share capital')], max_length=32)),
                ('calculation_note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
    ]
