# Generated by Django 5.2.12 on 2026-04-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neos_ceramica', '0002_ceramicaannualvaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceramicaannualvaluation',
            name='valuation_method',
            field=models.CharField(blank=True, choices=[('audited_balance', 'Balance aprobado auditado'), ('theoretical_value', 'Valor teorico contable'), ('earnings_capitalisation', 'Capitalizacion del beneficio a 3 anos'), ('nominal_value', 'Capital social nominal')], max_length=32),
        ),
    ]
