# Generated by Django 6.0.2 on 2026-03-22 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatementImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(blank=True, max_length=120)),
                ('account_label', models.CharField(blank=True, max_length=120)),
                ('iban', models.CharField(blank=True, max_length=34)),
                ('currency', models.CharField(default='EUR', max_length=8)),
                ('holder_name', models.CharField(blank=True, max_length=180)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('source_file', models.FileField(upload_to='banking/statements/%Y/%m')),
                ('source_filename', models.CharField(max_length=255)),
                ('file_checksum', models.CharField(max_length=64, unique=True)),
                ('import_status', models.CharField(choices=[('pending', 'Pending'), ('imported', 'Imported'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('opening_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_pension_contributions', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_dividends', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('error_message', models.TextField(blank=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-period_end', '-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='BankMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('value_date', models.DateField(blank=True, null=True)),
                ('concept', models.CharField(max_length=255)),
                ('normalized_concept', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('reference_1', models.CharField(blank=True, max_length=120)),
                ('reference_2', models.CharField(blank=True, max_length=120)),
                ('movement_group', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('pension', 'Pension contribution'), ('dividend', 'Stock dividend')], max_length=16)),
                ('concept_bucket', models.CharField(blank=True, max_length=120)),
                ('statement_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='banking.bankstatementimport')),
            ],
            options={
                'ordering': ['-booking_date', '-id'],
            },
        ),
    ]
