# Generated by Django 6.0.2 on 2026-03-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_bankstatementimport_bankmovement'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankInvestmentPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=120)),
                ('product_name', models.CharField(max_length=180)),
                ('product_type', models.CharField(choices=[('savings_plan', 'Savings plan'), ('life_savings', 'Life savings'), ('brokered_equity', 'Brokered equity'), ('other', 'Other')], default='other', max_length=24)),
                ('invested_amount_override', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('units', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('price_date', models.DateField(blank=True, null=True)),
                ('portfolio_weight_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('annual_income', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['institution', 'product_type', 'product_name'],
            },
        ),
    ]
