# Generated by Django 6.0.2 on 2026-04-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0003_bankinvestmentposition"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankbalance",
            name="ownership_category",
            field=models.CharField(
                choices=[("joint", "Conjunta"), ("ximo", "Ximo"), ("monica", "Monica")],
                default="joint",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="bankinvestmentposition",
            name="ownership_category",
            field=models.CharField(
                choices=[("joint", "Conjunta"), ("ximo", "Ximo"), ("monica", "Monica")],
                default="joint",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="bankstatementimport",
            name="ownership_category",
            field=models.CharField(
                choices=[("joint", "Conjunta"), ("ximo", "Ximo"), ("monica", "Monica")],
                default="joint",
                max_length=12,
            ),
        ),
    ]
