# Generated by Django 5.2.12 on 2026-04-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_bankbalance_bankinvestmentposition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankinvestmentposition',
            name='product_type',
            field=models.CharField(choices=[('savings_plan', 'Plan de ahorro'), ('life_savings', 'Ahorro vida'), ('brokered_equity', 'Acciones en custodia'), ('other', 'Otro')], default='other', max_length=24),
        ),
        migrations.AlterField(
            model_name='bankmovement',
            name='movement_group',
            field=models.CharField(choices=[('income', 'Ingreso'), ('expense', 'Gasto'), ('pension', 'Aportacion a plan'), ('dividend', 'Dividendo')], max_length=16),
        ),
        migrations.AlterField(
            model_name='bankstatementimport',
            name='import_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('imported', 'Importado'), ('failed', 'Fallido')], default='pending', max_length=20),
        ),
    ]
