# Generated by Django 5.2.12 on 2026-04-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_alter_bankinvestmentposition_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatementimport',
            name='statement_kind',
            field=models.CharField(choices=[('account', 'Cuenta'), ('card', 'Tarjeta')], default='account', max_length=16),
        ),
    ]
