# Generated by Django 5.2.12 on 2026-04-05 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0006_bankstatementimport_statement_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_category', models.CharField(choices=[('joint', 'Conjunta'), ('ximo', 'Ximo'), ('monica', 'Monica')], default='joint', max_length=12)),
                ('provider', models.CharField(choices=[('gocardless', 'GoCardless Open Banking')], default='gocardless', max_length=32)),
                ('institution_name', models.CharField(max_length=160)),
                ('institution_id', models.CharField(max_length=160)),
                ('country_code', models.CharField(default='ES', max_length=2)),
                ('reference', models.CharField(max_length=80, unique=True)),
                ('agreement_id', models.CharField(blank=True, max_length=64)),
                ('requisition_id', models.CharField(blank=True, max_length=64)),
                ('requisition_link', models.URLField(blank=True)),
                ('requisition_status', models.CharField(blank=True, max_length=16)),
                ('consent_expires_at', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['institution_name', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='bankstatementimport',
            name='import_source',
            field=models.CharField(choices=[('upload', 'Subida manual'), ('open_banking', 'Open banking')], default='upload', max_length=20),
        ),
        migrations.AlterField(
            model_name='bankstatementimport',
            name='source_file',
            field=models.FileField(blank=True, upload_to='banking/statements/%Y/%m'),
        ),
        migrations.AddField(
            model_name='bankstatementimport',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statement_imports', to='banking.bankconnection'),
        ),
        migrations.CreateModel(
            name='BankExternalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_category', models.CharField(choices=[('joint', 'Conjunta'), ('ximo', 'Ximo'), ('monica', 'Monica')], default='joint', max_length=12)),
                ('statement_kind', models.CharField(choices=[('account', 'Cuenta'), ('card', 'Tarjeta')], default='account', max_length=16)),
                ('provider_account_id', models.CharField(max_length=80, unique=True)),
                ('institution', models.CharField(blank=True, max_length=120)),
                ('account_label', models.CharField(max_length=180)),
                ('iban', models.CharField(blank=True, max_length=34)),
                ('currency', models.CharField(default='EUR', max_length=8)),
                ('holder_name', models.CharField(blank=True, max_length=180)),
                ('linked_account_name', models.CharField(blank=True, max_length=180)),
                ('raw_details', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('last_imported_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_accounts', to='banking.bankconnection')),
            ],
            options={
                'ordering': ['institution', 'account_label', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='bankstatementimport',
            name='external_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statement_imports', to='banking.bankexternalaccount'),
        ),
    ]
