# Generated by Django 5.2.12 on 2026-04-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0007_bankconnection_bankstatementimport_import_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatementimport',
            name='import_source',
            field=models.CharField(choices=[('upload', 'Subida manual'), ('open_banking', 'Open banking'), ('robot', 'Robot local')], default='upload', max_length=20),
        ),
    ]
