# Generated by Django 5.2.12 on 2026-04-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0008_alter_bankstatementimport_import_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankinvestmentposition",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("investment_fund", "Fondo de inversion"),
                    ("savings_plan", "Plan de ahorro"),
                    ("life_savings", "Ahorro vida"),
                    ("brokered_equity", "Acciones en custodia"),
                    ("other", "Otro"),
                ],
                default="other",
                max_length=24,
            ),
        ),
    ]
