# Generated by Django 6.0.2 on 2026-03-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditivesHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_name', models.CharField(max_length=150)),
                ('invested_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('current_valuation', models.DecimalField(decimal_places=2, max_digits=14)),
                ('annual_dividend_income', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['investment_name'],
            },
        ),
    ]
