# Generated by Django 5.2.12 on 2026-04-27 15:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VentureOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=180, unique=True)),
                ('website', models.URLField(blank=True)),
                ('sector', models.CharField(blank=True, max_length=140)),
                ('geography', models.CharField(blank=True, max_length=120)),
                ('stage', models.CharField(choices=[('early', 'Estadio inicial'), ('growth_issues', 'Problemas de crecimiento'), ('turnaround', 'Reestructuracion'), ('scaleup', 'Escalado'), ('other', 'Otro')], default='early', max_length=24)),
                ('status', models.CharField(choices=[('screening', 'Primer filtro'), ('research', 'En analisis'), ('due_diligence', 'Due diligence'), ('negotiation', 'Negociacion'), ('on_hold', 'En pausa'), ('approved', 'Aprobada'), ('rejected', 'Descartada')], default='screening', max_length=24)),
                ('strategic_fit', models.CharField(choices=[('ceramica', 'Neos Ceramica'), ('additives', 'Neos Additives'), ('both', 'Ceramica + Additives'), ('group', 'Grupo Neos'), ('other', 'Otro encaje')], default='both', max_length=24)),
                ('contact_name', models.CharField(blank=True, max_length=140)),
                ('source', models.CharField(blank=True, max_length=160)),
                ('identified_on', models.DateField(default=django.utils.timezone.localdate)),
                ('next_review_on', models.DateField(blank=True, null=True)),
                ('ticket_min', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('ticket_max', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('estimated_valuation', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('annual_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('ebitda', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('cash_need', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('neos_fit_score', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('market_score', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('team_score', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('financial_score', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('risk_control_score', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('fit_summary', models.TextField(blank=True)),
                ('growth_issue', models.TextField(blank=True)),
                ('synergy_notes', models.TextField(blank=True)),
                ('diligence_notes', models.TextField(blank=True)),
                ('red_flags', models.TextField(blank=True)),
                ('next_steps', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['status', '-next_review_on', '-updated_at', 'company_name'],
            },
        ),
        migrations.CreateModel(
            name='VentureDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('file', models.FileField(upload_to='venture_studies/%Y/%m')),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='venture_studies.ventureopportunity')),
            ],
            options={
                'ordering': ['-uploaded_at', 'title'],
            },
        ),
    ]
