# Generated by Django 5.2.12 on 2026-04-27 15:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venture_studies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venturedocument',
            name='document_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venturedocument',
            name='document_kind',
            field=models.CharField(choices=[('balance', 'Balance o cuentas anuales'), ('pitch', 'Presentacion'), ('contract', 'Contrato o pedido'), ('other', 'Otro documento')], default='balance', max_length=16),
        ),
        migrations.AddField(
            model_name='venturedocument',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='venturedocument',
            name='extraction_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='venturedocument',
            name='extraction_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('extracted', 'Texto extraido'), ('failed', 'Error de lectura')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='venturedocument',
            name='fiscal_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VentureAnalysisSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateField(default=django.utils.timezone.localdate)),
                ('recommendation', models.CharField(choices=[('buy', 'Compra'), ('watch', 'Vigilancia')], default='watch', max_length=12)),
                ('confidence', models.CharField(choices=[('high', 'Alta'), ('medium', 'Media'), ('low', 'Baja')], default='medium', max_length=12)),
                ('score_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('valuation_low', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('valuation_base', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('valuation_high', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('suggested_purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('suggested_ticket', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('target_ownership_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('annual_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('ebitda', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('net_equity', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('net_debt', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('cash_need', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('summary', models.TextField(blank=True)),
                ('valuation_note', models.TextField(blank=True)),
                ('web_summary', models.TextField(blank=True)),
                ('drivers', models.JSONField(blank=True, default=list)),
                ('risks', models.JSONField(blank=True, default=list)),
                ('assumptions', models.JSONField(blank=True, default=list)),
                ('web_context', models.JSONField(blank=True, default=dict)),
                ('analysis_payload', models.JSONField(blank=True, default=dict)),
                ('agent_provider', models.CharField(default='core', max_length=32)),
                ('agent_label', models.CharField(default='Analisis interno', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_snapshots', to='venture_studies.ventureopportunity')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_snapshots', to='venture_studies.venturedocument')),
            ],
            options={
                'ordering': ['-analysis_date', '-created_at', '-id'],
            },
        ),
    ]
