# Generated by Django 5.2.12 on 2026-04-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venture_studies', '0002_venturedocument_document_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventureopportunity',
            name='address',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='ventureopportunity',
            name='cnae_code',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='ventureopportunity',
            name='cnae_label',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='ventureopportunity',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='ventureopportunity',
            name='employees',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventureopportunity',
            name='legal_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='ventureopportunity',
            name='phone',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='ventureopportunity',
            name='tax_id',
            field=models.CharField(blank=True, db_index=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='venturedocument',
            name='document_kind',
            field=models.CharField(choices=[('balance', 'Balance o cuentas anuales'), ('informa', 'Informe Informa'), ('pitch', 'Presentacion'), ('contract', 'Contrato o pedido'), ('other', 'Otro documento')], default='balance', max_length=16),
        ),
    ]
