# Generated by Django 5.2.12 on 2026-04-28 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venture_studies', '0003_ventureopportunity_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentureDiscoveryCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=180)),
                ('website', models.URLField(blank=True)),
                ('sector', models.CharField(blank=True, max_length=140)),
                ('geography', models.CharField(blank=True, max_length=120)),
                ('source_title', models.CharField(blank=True, max_length=240)),
                ('source_url', models.URLField(blank=True)),
                ('source_label', models.CharField(blank=True, max_length=120)),
                ('summary', models.TextField(blank=True)),
                ('rationale', models.TextField(blank=True)),
                ('score_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('new', 'Nueva'), ('promoted', 'Incorporada'), ('rejected', 'Descartada')], default='new', max_length=16)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('promoted_opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_discovery_sources', to='venture_studies.ventureopportunity')),
            ],
            options={
                'ordering': ['status', '-score_pct', '-discovered_at', 'company_name'],
                'unique_together': {('company_name', 'source_url')},
            },
        ),
    ]
