# Generated by Django 5.2.12 on 2026-04-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venture_studies', '0004_venturediscoverycandidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venturedocument',
            name='document_kind',
            field=models.CharField(choices=[('balance', 'Balance o cuentas anuales'), ('informa', 'Informe Informa'), ('dossier', 'Dossier financiero/comercial'), ('pitch', 'Presentacion'), ('contract', 'Contrato o pedido'), ('other', 'Otro documento')], default='balance', max_length=16),
        ),
    ]
