# Generated by Django 5.2.12 on 2026-04-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venture_studies', '0005_alter_venturedocument_document_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venturediscoverycandidate',
            name='source_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
