# Generated by Django 6.0.2 on 2026-03-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseholdAlertSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=50, unique=True)),
                ('total_monthly_expense_limit', models.DecimalField(decimal_places=2, default=8000, max_digits=14)),
                ('concept_monthly_expense_limit', models.DecimalField(decimal_places=2, default=1500, max_digits=14)),
                ('expense_spike_threshold_pct', models.DecimalField(decimal_places=2, default=25, max_digits=7)),
                ('lookback_months', models.PositiveSmallIntegerField(default=3)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Household alert settings',
            },
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(unique=True)),
                ('invested_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('annual_income', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_return_eur', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_return_pct', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('section_values', models.JSONField(blank=True, default=dict)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['snapshot_date'],
            },
        ),
    ]
