# Generated by Django 6.0.2 on 2026-05-02 05:35

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedInvestmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_category', models.CharField(choices=[('joint', 'Conjunta'), ('ximo', 'Ximo'), ('monica', 'Monica')], default='joint', max_length=12)),
                ('title', models.CharField(max_length=180)),
                ('investment_block', models.CharField(choices=[('equities', 'Acciones cotizadas'), ('unlisted', 'Empresa no cotizada'), ('real_estate', 'Inmuebles'), ('banking_product', 'Producto bancario'), ('neos_group', 'Grupo Neos'), ('other', 'Otro')], default='equities', max_length=24)),
                ('flow_type', models.CharField(choices=[('outflow', 'Pago previsto'), ('inflow', 'Cobro previsto')], default='outflow', max_length=12)),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('planned', 'Previsto'), ('paid', 'Realizado'), ('cancelled', 'Cancelado')], default='planned', max_length=16)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['status', 'due_date', 'title'],
            },
        ),
    ]
