# Generated by Django 5.2.13 on 2026-05-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_plannedinvestmentpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesForecastSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(unique=True)),
                ('forecast_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('forecast_purchase_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('forecast_units', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('forecast_average_purchase_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('forecast_average_sale_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('actual_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('actual_purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('actual_units', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('actual_average_purchase_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('actual_average_sale_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('source_label', models.CharField(blank=True, default='sales', max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['month'],
            },
        ),
    ]
