# Generated by Django 6.0.2 on 2026-03-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquityPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.CharField(max_length=120)),
                ('ticker', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=160)),
                ('shares', models.DecimalField(decimal_places=4, max_digits=14)),
                ('average_cost_per_share', models.DecimalField(decimal_places=4, max_digits=14)),
                ('current_price_per_share', models.DecimalField(decimal_places=4, max_digits=14)),
                ('annual_dividend_income', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ticker'],
            },
        ),
    ]
