# Generated by Django 6.0.2 on 2026-04-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equities", "0002_equityposition_benchmark_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="equityposition",
            name="ownership_category",
            field=models.CharField(
                choices=[("joint", "Conjunta"), ("ximo", "Ximo"), ("monica", "Monica")],
                default="joint",
                max_length=12,
            ),
        ),
    ]
