# Generated by Django 5.2.12 on 2026-04-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equities', '0003_equityposition_ownership_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='equityposition',
            name='annual_maintenance_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='equitypricehistory',
            name='high_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='equitypricehistory',
            name='low_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='equitypricehistory',
            name='open_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
    ]
