# Generated by Django 5.2.12 on 2026-04-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equities', '0006_alter_equityposition_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equityposition',
            name='reference_profile',
            field=models.CharField(choices=[('market_index', 'Indice o activo cotizado'), ('euribor_12m', 'Euribor 12 meses'), ('spain_house_price', 'Precio vivienda Espana'), ('spain_electricity_demand', 'Demanda electrica Espana'), ('spain_gas_consumption', 'Consumo de gas Espana')], default='market_index', max_length=24),
        ),
    ]
