# Generated by Django 5.2.12 on 2026-04-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equities', '0007_alter_equityposition_reference_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='equityposition',
            name='trade_channel',
            field=models.CharField(choices=[('app', 'App'), ('web', 'Web'), ('office', 'Oficina'), ('contact_center', 'Contact Center'), ('other', 'Otro')], default='app', max_length=24),
        ),
    ]
