# Generated by Django 5.2.12 on 2026-04-12 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equities", "0008_equityposition_trade_channel"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquityTicketSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("snapshot_date", models.DateField()),
                ("invested_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("current_value", models.DecimalField(decimal_places=2, max_digits=14)),
                ("projected_market_value_12m", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("projected_total_value_12m", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("projected_price_12m", models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_snapshots",
                        to="equities.equityposition",
                    ),
                ),
            ],
            options={
                "ordering": ["snapshot_date", "position_id"],
                "unique_together": {("position", "snapshot_date")},
            },
        ),
    ]
