# Generated by Django 5.2.12 on 2026-04-12 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equities', '0009_equityticketsnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquityOptimizationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.CharField(max_length=40, unique=True)),
                ('label', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'En proceso'), ('completed', 'Completada'), ('failed', 'Fallida')], default='pending', max_length=16)),
                ('status_note', models.CharField(blank=True, max_length=255)),
                ('total_investment', models.DecimalField(decimal_places=2, max_digits=14)),
                ('max_company_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_sector_positions', models.PositiveIntegerField(default=0)),
                ('restrictions_note', models.TextField(blank=True)),
                ('summary_data', models.JSONField(blank=True, default=dict)),
                ('allocations_data', models.JSONField(blank=True, default=list)),
                ('report_html', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equity_optimization_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
