# Generated by Django 5.2.12 on 2026-04-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equities', '0010_equityoptimizationrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='equityoptimizationrun',
            name='progress_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
