# Generated by Django 5.2.12 on 2026-04-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equities', '0011_equityoptimizationrun_progress_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='equityoptimizationrun',
            name='report_pdf_html',
            field=models.TextField(blank=True),
        ),
    ]
