# Generated by Django 5.2.12 on 2026-04-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equities', '0012_equityoptimizationrun_report_pdf_html'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquityClosedPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_category', models.CharField(choices=[('joint', 'Conjunta'), ('ximo', 'Ximo'), ('monica', 'Monica')], default='joint', max_length=12)),
                ('broker', models.CharField(max_length=120)),
                ('ticker', models.CharField(max_length=20)),
                ('quote_symbol', models.CharField(blank=True, max_length=40)),
                ('company_name', models.CharField(max_length=160)),
                ('trade_channel', models.CharField(choices=[('app', 'App'), ('web', 'Web'), ('office', 'Oficina'), ('contact_center', 'Contact Center'), ('other', 'Otro')], default='app', max_length=24)),
                ('benchmark_symbol', models.CharField(blank=True, default='^IBEX', max_length=40)),
                ('benchmark_name', models.CharField(blank=True, default='IBEX 35', max_length=120)),
                ('opened_on', models.DateField(blank=True, null=True)),
                ('closed_on', models.DateField()),
                ('shares', models.DecimalField(decimal_places=4, max_digits=14)),
                ('average_cost_per_share', models.DecimalField(decimal_places=4, max_digits=14)),
                ('sale_price_per_share', models.DecimalField(decimal_places=4, max_digits=14)),
                ('purchase_total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sale_total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('maintenance_cost_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_dividend_income_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('archived_price_history', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-closed_on', 'ticker'],
            },
        ),
        migrations.AddField(
            model_name='equityposition',
            name='opened_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
