# Generated by Django 5.2.12 on 2026-04-17 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equities', '0016_equitynightlyanalysisrun_and_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquityPurchaseForecastBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_analysis_date', models.DateField()),
                ('baseline_date', models.DateField()),
                ('analysis_scope', models.CharField(blank=True, default='ibex', max_length=16)),
                ('analysis_key', models.CharField(blank=True, max_length=80)),
                ('reference_label', models.CharField(blank=True, max_length=120)),
                ('trade_alert_label', models.CharField(blank=True, max_length=32)),
                ('reliability_label', models.CharField(blank=True, max_length=32)),
                ('safety_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('baseline_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('projected_price_1y', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('projected_price_2y', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('projected_price_3y', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('projected_price_4y', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('projected_price_5y', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('projected_return_pct_1y', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('projected_return_pct_2y', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('projected_return_pct_3y', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('projected_return_pct_4y', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('projected_return_pct_5y', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_forecast_baseline', to='equities.equityposition')),
                ('source_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_forecast_baselines', to='equities.equitynightlyanalysisrun')),
            ],
            options={
                'ordering': ['-source_analysis_date', '-id'],
            },
        ),
    ]
