# Generated by Django 5.2.12 on 2026-04-26 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equities', '0019_equitypurchaseforecastbaseline_projected_path_5y'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquityExpectationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateField()),
                ('review_kind', models.CharField(choices=[('scheduled', 'Programada'), ('forced', 'Forzada'), ('news_shock', 'Shock de noticias'), ('carry_forward', 'Arrastre')], default='scheduled', max_length=16)),
                ('scope', models.CharField(choices=[('tracked', 'Seguimiento guardado'), ('ibex', 'Radar IBEX')], max_length=16)),
                ('analysis_key', models.CharField(max_length=80)),
                ('ticker', models.CharField(max_length=20)),
                ('quote_symbol', models.CharField(blank=True, max_length=40)),
                ('company_name', models.CharField(max_length=160)),
                ('status_key', models.CharField(blank=True, max_length=24)),
                ('sector_label', models.CharField(blank=True, max_length=120)),
                ('reference_label', models.CharField(blank=True, max_length=120)),
                ('trade_alert_label', models.CharField(blank=True, max_length=32)),
                ('trade_alert_tone', models.CharField(blank=True, max_length=16)),
                ('safety_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('reliability_label', models.CharField(blank=True, max_length=32)),
                ('reliability_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('current_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('projected_return_pct_1y', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('projected_return_pct_5y', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('expected_return_pct_1y', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('expected_return_pct_2y', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('expected_return_pct_3y', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('expected_return_pct_4y', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('expected_return_pct_5y', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('projection_12m_scenario_rows', models.JSONField(blank=True, default=list)),
                ('cycle_5y_scenario_rows', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expectation_reviews', to='equities.equityposition')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expectation_reviews', to='equities.equitynightlyanalysisrun')),
            ],
            options={
                'ordering': ['-analysis_date', 'scope', 'company_name', 'ticker'],
                'unique_together': {('run', 'analysis_key')},
            },
        ),
    ]
